---
name: Docker-Build
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: private
    permissions:
      contents: read
    steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
        - uses: docker/login-action@v3
          with:
            registry: ${{ secrets.OXEYE_REGISTRY }}
            username: ${{ secrets.OXEYE_REGISTRY_USERNAME }}
            password: ${{ secrets.OXEYE_REGISTRY_PASSWORD }}
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ${{ secrets.OXEYE_REGISTRY }}/dp-otel-collector-deduplicator
            tags: |
              type=sha,format=long,prefix=sha-
              type=ref,event=branch
              type=semver,pattern=v{{version}}
              type=semver,pattern=v{{major}}.{{minor}}
        - name: Docker build
          uses: docker/build-push-action@v3
          with:
            push: true
            context: .
            file: cmd/otelcontribcol/Dockerfile
            cache-from: type=gha,scope=${{ github.ref_name }}-opentelemetry-collector
            cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-opentelemetry-collector
            tags: ${{ steps.meta.outputs.tags }}
