---
name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Create Git Tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          WITH_V: true
