---
name: Release
on:
  push:
    # branches: [main]
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Create Git Tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_GITHUB_TOKEN }}
          WITH_V: true
